// Code generated by protoc-gen-go. DO NOT EDIT.
// source: http.proto

package uwsgifuzz

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Header) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type HttpRequest struct {
	Method               []byte    `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Uri                  []byte    `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Version              []byte    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Headers              []*Header `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty"`
	Body                 []byte    `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HttpRequest) Reset()         { *m = HttpRequest{} }
func (m *HttpRequest) String() string { return proto.CompactTextString(m) }
func (*HttpRequest) ProtoMessage()    {}
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{1}
}

func (m *HttpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRequest.Unmarshal(m, b)
}
func (m *HttpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRequest.Marshal(b, m, deterministic)
}
func (m *HttpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRequest.Merge(m, src)
}
func (m *HttpRequest) XXX_Size() int {
	return xxx_messageInfo_HttpRequest.Size(m)
}
func (m *HttpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRequest proto.InternalMessageInfo

func (m *HttpRequest) GetMethod() []byte {
	if m != nil {
		return m.Method
	}
	return nil
}

func (m *HttpRequest) GetUri() []byte {
	if m != nil {
		return m.Uri
	}
	return nil
}

func (m *HttpRequest) GetVersion() []byte {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *HttpRequest) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HttpRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "uwsgifuzz.Header")
	proto.RegisterType((*HttpRequest)(nil), "uwsgifuzz.HttpRequest")
}

func init() { proto.RegisterFile("http.proto", fileDescriptor_11b04836674e6f94) }

var fileDescriptor_11b04836674e6f94 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xcd, 0x8a, 0x83, 0x40,
	0x10, 0x84, 0x71, 0x5d, 0x47, 0xb6, 0xdd, 0xc3, 0x6e, 0x13, 0xc2, 0x1c, 0xc5, 0x93, 0x10, 0x90,
	0x90, 0xbc, 0x84, 0x67, 0xdf, 0x40, 0xb1, 0x13, 0x25, 0x3f, 0x63, 0x66, 0x7a, 0x0c, 0xfa, 0x18,
	0x79, 0xe2, 0xe0, 0xa8, 0xb9, 0x55, 0x15, 0x5d, 0xc5, 0xd7, 0x00, 0x0d, 0x73, 0x97, 0x75, 0x5a,
	0xb1, 0xc2, 0x1f, 0xfb, 0x34, 0xe7, 0xf6, 0x64, 0xc7, 0x31, 0xd9, 0x83, 0xc8, 0xa9, 0xac, 0x49,
	0xe3, 0x1f, 0xf8, 0x17, 0x1a, 0xa4, 0x17, 0x7b, 0xe9, 0x6f, 0x31, 0x49, 0xdc, 0x40, 0xd0, 0x97,
	0x57, 0x4b, 0xf2, 0xcb, 0x65, 0xb3, 0x49, 0x5e, 0x1e, 0x44, 0x39, 0x73, 0x57, 0xd0, 0xc3, 0x92,
	0x61, 0xdc, 0x82, 0xb8, 0x11, 0x37, 0xaa, 0x5e, 0xaa, 0x8b, 0x9b, 0xf6, 0xac, 0x6e, 0x97, 0xee,
	0x24, 0x51, 0x42, 0xd8, 0x93, 0x36, 0xad, 0xba, 0x4b, 0xdf, 0xa5, 0xab, 0xc5, 0x1d, 0x84, 0x8d,
	0xa3, 0x30, 0x32, 0x88, 0xfd, 0x34, 0x3a, 0xfc, 0x67, 0x1f, 0xc4, 0x6c, 0xe6, 0x2b, 0xd6, 0x0b,
	0x44, 0xf8, 0xae, 0x54, 0x3d, 0x48, 0xe1, 0x36, 0x9c, 0xae, 0x84, 0x7b, 0xec, 0xf8, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0xf4, 0x88, 0x1b, 0x87, 0xe6, 0x00, 0x00, 0x00,
}
